"use client";

/* eslint-disable react/no-unescaped-entities */
import { useEffect } from "react";
import "../../deck/deck.css";
import "../../deck/connectors.css";
import "./session-4.css";

type SlideProps={n:number;title:string;subtitle?:string;section?:string;source?:string;className?:string;children:React.ReactNode};
function Slide({n,title,subtitle,section="SESSION 4  |  COMMIT + LEARN",source,className="",children}:SlideProps){return <section className={`consulting-slide ${className}`} id={`slide-${n}`}><header className="slide-header"><div className="section-label">{section}</div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</header><div className="slide-content">{children}</div><footer className="slide-footer"><span>{source?`Source: ${source}`:"Core PM course synthesis"}</span><b>{String(n).padStart(2,"0")}</b></footer></section>}
function ExhibitTitle({n,children}:{n:number;children:React.ReactNode}){return <div className="exhibit-title"><b>Exhibit {n}</b><span>{children}</span></div>}
function PromptSlide({n,unit,title,output,children}:{n:number;unit:string;title:string;output:string;children:React.ReactNode}){return <Slide n={n} section={`${unit}  |  MAKE THE CALL`} title={title} className="prompt"><div className="prompt-layout"><div className="prompt-flag"><span>INDIVIDUAL DECISION</span><b>06 min</b></div><div className="prompt-question">{children}</div><div className="prompt-output"><span>OUTPUT</span><p>{output}</p></div></div></Slide>}

export default function Session4Deck(){
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{const forward=["ArrowRight","ArrowDown","PageDown"],backward=["ArrowLeft","ArrowUp","PageUp"];if(![...forward,...backward].includes(event.key))return;event.preventDefault();const slides=[...document.querySelectorAll<HTMLElement>(".consulting-slide")];const current=slides.reduce((best,slide,index)=>Math.abs(slide.getBoundingClientRect().top)<Math.abs(slides[best].getBoundingClientRect().top)?index:best,0);const next=current+(forward.includes(event.key)?1:-1);slides[Math.max(0,Math.min(slides.length-1,next))]?.scrollIntoView({behavior:"smooth"})};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
  return <main className="consulting-deck session-four"><aside className="deck-controls"><span>Use arrow keys</span><button onClick={()=>document.documentElement.requestFullscreen()}>Fullscreen</button></aside>

    <Slide n={1} title="Make the choice survivable" subtitle="Session 4 | Carry a consequential choice through execution while preserving ownership and honest learning" className="cover"><div className="cover-grid"><div className="cover-number">04</div><div className="cover-steps"><div><span>10</span><b>Create commitment</b><small>Differentiate input, authority, confidence, dissent, and exact asks.</small></div><div><span>11</span><b>Adapt execution</b><small>Change sequence and controls while preserving explicit ownership.</small></div><div><span>12</span><b>Close the loop</b><small>Compare forecast with outcome and improve the operating system.</small></div></div></div></Slide>

    <Slide n={2} title="Session 4 tests whether the decision remains intact through people, delivery, and outcome" subtitle="Commitment enables action; adaptation contains consequence; honest review improves the next decision"><ExhibitTitle n={1}>The decision-survival loop</ExhibitTitle><div className="survival-loop"><article><em>1</em><b>Commit</b><p>Make context, participation, authority, confidence, dissent, and asks explicit.</p></article><i/><article><em>2</em><b>Adapt</b><p>Re-sequence dependencies, change review depth, and intervene proportionally.</p></article><i/><article><em>3</em><b>Expose</b><p>Release progressively with product, operational, and measurement boundaries.</p></article><i/><article><em>4</em><b>Learn</b><p>Compare the forecast with the result and improve the product and system.</p></article></div><div className="implication"><b>Week 4 output</b><span>A completed Product Decision Case ready for the Week 5 Demo Day—not a shipping retrospective.</span></div></Slide>

    <Slide n={3} section="NOTED  |  WEEK 4 CONSEQUENCE RELEASE" title="The direction survived planning; commitment, delivery, and outcome now expose different weaknesses" subtitle="The product context is real; stakeholders, delivery changes, exposure, and outcomes are constructed for practice" source="Noted teaching case; product context from noted-main; Week 4 evidence constructed for practice"><ExhibitTitle n={2}>Three moments in the same Noted decision</ExhibitTitle><div className="week-four-release"><article><small>COMMITMENT TENSION</small><b>Sales prefers broad summary intelligence</b><p>Product chose enterprise decision handoff; the accountable owner has not named how dissent is retained.</p></article><article><small>DELIVERY CHANGE</small><b>Permission work grows from two to four weeks</b><p>Workspace identity depends on an external provider; the PM is tempted to take over the plan.</p></article><article><small>STAGED OUTCOME</small><b>+3 pp confirmed follow-through</b><p>Below the +8 pp forecast; one workspace is positive, one blocked by governance, and 12% of actors are unobserved.</p></article><div className="case-call"><b>Governing question</b><span>What must Noted preserve, change, and learn without dissolving ownership or rewriting the original choice?</span></div></div></Slide>

    <Slide n={4} section="UNIT 10  |  PORTABLE CONTEXT" title="Commitment starts when people can act from the context—not when they receive more implementation detail" subtitle="Communicate the opportunity, audience, evidence, success, constraints, and exclusions; leave implementation judgment where it belongs" source="Reforge, Empowering Context; Narrative, Commitments, Tasks"><ExhibitTitle n={3}>Context that enables the Noted team to decide locally</ExhibitTitle><div className="context-stack"><article><small>WHY THIS</small><b>Trusted ownership handoff is the current enterprise constraint.</b><p>Week 2 evidence narrowed the problem; Week 3 chose workflow depth.</p></article><article><small>FOR WHOM</small><b>Team leads in recurring decision-heavy enterprise meetings.</b><p>Not every meeting and not every individual knowledge worker.</p></article><article><small>SUCCESS + GUARDRAILS</small><b>Improve confirmed follow-through without weakening trust or governance.</b><p>Stage exposure; instrument actor and meeting type before broad use.</p></article><article><small>BOUNDARY</small><b>Do not prescribe the internal permission architecture.</b><p>Engineering owns implementation within the product and risk constraints.</p></article></div><div className="implication"><b>Portable context</b><span>More context and fewer unnecessary implementation decisions create room for responsible local judgment.</span></div></Slide>

    <Slide n={5} section="UNIT 10  |  PARTICIPATION + AUTHORITY" title="Awareness, input, alignment, and decision authority are different jobs" subtitle="Authority is decision-specific: Product owns direction; domain owners retain decisions inside their remit" source="Reforge, Awareness, Alignment, Inclusion; Opinionated Decision-Making; course synthesis"><ExhibitTitle n={4}>Noted participation and decision-right map</ExhibitTitle><div className="rights-map"><div className="ring awareness"><span>AWARENESS</span><b>Support · GTM · Finance</b></div><div className="ring alignment"><span>INPUT + ALIGNMENT</span><b>Sales · Security · Customer Success</b></div><div className="ring inclusion"><span>SHAPE THE WORK</span><b>Engineering · Design · Data</b></div><div className="ring authority"><span>PRODUCT-DIRECTION OWNER</span><b>Product lead</b></div><div className="dissent-card"><small>UNRESOLVED DISSENT</small><b>Sales believes personal summary breadth will create pipeline faster.</b><p>Record the disagreement, evidence, and reopening trigger. Do not disguise it as alignment.</p></div></div></Slide>

    <Slide n={6} section="UNIT 10  |  DUAL CONFIDENCE" title="Product confidence and engineering confidence answer different questions—and both constrain commitment" subtitle="Opportunity conviction cannot substitute for feasibility, effort, integration, and risk understanding" source="Reforge, Product Conviction; Effort and Alignment"><ExhibitTitle n={5}>Two confidence tracks before Noted commits</ExhibitTitle><div className="confidence-tracks"><div className="track product"><small>PRODUCT CONFIDENCE</small><b>Do we understand the problem, value, impact pathway, and decision rule?</b><span className="level high">HIGH ENOUGH TO STAGE</span><ul><li>Problem mechanism plausible</li><li>Target segment bounded</li><li>Production impact still uncertain</li></ul></div><div className="track engineering"><small>ENGINEERING CONFIDENCE</small><b>Do we understand effort, dependencies, failure modes, integration, and operability?</b><span className="level low">LOW ON PERMISSIONS</span><ul><li>Identity provider dependency unresolved</li><li>Estimate range doubled</li><li>Rollback remains feasible</li></ul></div><div className="commit-boundary"><b>Commit now</b><span>Manual workflow and shadow-mode learning</span><b>Do not commit yet</b><span>Broad enterprise rollout or fixed launch date</span></div></div></Slide>

    <Slide n={7} section="UNIT 10  |  DISSENT + ASK" title="Commitment preserves dissent and makes the next organizational ask exact" subtitle="Escalate the decision, input, resource, or protection required—not a vague request for support" source="Reforge, Opinionated Decision-Making; Making Clear Asks"><ExhibitTitle n={6}>A commitment record leadership can act on</ExhibitTitle><div className="commitment-record"><article><small>DECIDED</small><b>Stage enterprise decision handoff; defer horizontal summary breadth.</b></article><article><small>DISSENT RETAINED</small><b>Sales expects broader summaries to create pipeline faster.</b><p>Reopen only if the admin distribution test fails or enterprise access blocks learning.</p></article><article><small>EXACT ASK</small><b>Choose one: add identity-platform support for two weeks, or narrow the pilot to manual provisioning.</b><p>Decision needed by Tuesday; accountable executive: CTO.</p></article><article><small>CONSEQUENCE</small><b>No choice means no credible enterprise exposure this cycle.</b><p>Do not convert the missing decision into an invisible team commitment.</p></article></div></Slide>

    <PromptSlide n={8} unit="UNIT 10" title="What must be true, owned, and understood for Noted to commit?" output="State the owner, differentiated participation, product and engineering confidence, retained dissent, and one exact escalation ask."><p>Define the decision owner, each stakeholder's participation level, product confidence, engineering confidence, and unresolved dissent.</p><strong>Make one exact escalation ask with owner, deadline, and consequence of no decision.</strong></PromptSlide>

    <Slide n={9} section="UNIT 11  |  DELIVERY SYSTEM" title="Delivery is an interdependent confidence-and-adaptation system—not a stream of tickets" subtitle="When reality changes, update sequence, interfaces, review depth, or commitment before changing ownership" source="Reforge, Delivery Systems at Scale; Dynamic Delivery Plans; Execution and Adaptation"><ExhibitTitle n={7}>Where adaptation can occur without taking the work back</ExhibitTitle><div className="delivery-system"><article><small>CONFIDENCE</small><b>What do product and engineering know—and not know?</b></article><i/><article><small>PLAN</small><b>Which milestones, dependencies, interfaces, and owners carry the choice?</b></article><i/><article><small>ADAPT</small><b>What changes as evidence, effort, or risk becomes clearer?</b></article><i/><article><small>EXPOSE</small><b>How is consequence contained while the team learns?</b></article><div className="system-warning"><b>Failure mode</b><span>The PM responds to uncertainty by writing the plan, resolving every interface, and becoming the integration owner.</span></div></div></Slide>

    <Slide n={10} section="UNIT 11  |  RE-SEQUENCE" title="A changed dependency should alter the execution path before it silently consumes the commitment" subtitle="Sequence around uncertainty, unblockers, and value-bearing evidence—not the emotional pull of the original date" source="Reforge, Estimate Effort; Sequence Work; Mitigating Risks"><ExhibitTitle n={8}>Noted's revised path after the identity dependency appears</ExhibitTitle><div className="resequence"><div className="original"><small>ORIGINAL PLAN</small><b>Permissions</b><i/><b>Intelligence</b><i/><b>Two-partner pilot</b><span>Permission estimate: 2 weeks</span></div><div className="changed"><small>REVISED PLAN</small><b>Manual provisioning for Partner A</b><i/><b>Shadow-mode handoff intelligence</b><i/><b>Identity spike + Partner B hold</b><span>Learning continues while the dependency is resolved.</span></div><div className="decision-note"><b>Stable direction</b><span>Enterprise handoff remains the strategy.</span><b>Changed commitment</b><span>Broad provisioning and fixed timing are removed.</span></div></div></Slide>

    <Slide n={11} section="UNIT 11  |  INTERFACES" title="Delegation holds when outcomes, interfaces, decisions, dependencies, and integration points are explicit" subtitle="Ownership does not require isolation; collaboration does not require the PM to become the substitute owner" source="Reforge, Delegate and Manage; Kick-Off Content; course synthesis"><ExhibitTitle n={9}>Delegation contract for the permission dependency</ExhibitTitle><div className="interface-contract"><div className="contract-head"><span>Workstream</span><span>Owned outcome</span><span>Decision right</span><span>Interface + dependency</span><span>Integration check</span></div><div><b>Engineering</b><span>Safe workspace access path</span><span>Architecture and implementation</span><span>Identity provider; security controls</span><em>Threat model + demo</em></div><div><b>Product</b><span>Bounded pilot decision</span><span>Audience, value threshold, scope trade-off</span><span>Design partners; outcome semantics</span><em>Decision review</em></div><div><b>Security</b><span>Accepted exposure boundary</span><span>Control approval or explicit block</span><span>Retention, access, deletion</span><em>Risk sign-off</em></div><div><b>Customer Success</b><span>Partner readiness and recovery path</span><span>Onboarding execution</span><span>Admin availability; support process</span><em>Launch rehearsal</em></div></div><div className="implication"><b>PM boundary</b><span>Resolve the product trade-off and interface ambiguity. Do not absorb engineering, security, or launch ownership.</span></div></Slide>

    <Slide n={12} section="UNIT 11  |  REVIEW + INTERVENTION" title="Increase review and intervention with consequence—then name the condition for giving control back" subtitle="Product review should provide input and resolve questions; temporary control should not become permanent dependency" source="Reforge, Input Not Oversight; Team Touchpoints; Selective Micromanagement"><ExhibitTitle n={10}>Proportionate intervention ladder</ExhibitTitle><div className="intervention-ladder"><article><span>1</span><small>LOW CONSEQUENCE</small><b>Async update</b><p>Owner decides; PM stays informed.</p></article><article><span>2</span><small>COORDINATION RISK</small><b>Triggered review</b><p>Resolve one interface or product question.</p></article><article><span>3</span><small>MATERIAL EXPOSURE</small><b>Temporary tighter controls</b><p>More frequent review, explicit stop rule, named escalation.</p></article><article><span>4</span><small>AUTHORITY OR SAFETY BLOCK</small><b>Pause or escalate</b><p>Do not force execution through an unresolved boundary.</p></article></div><div className="return-condition"><b>Return autonomy when</b><span>the identity path is validated, interfaces have owners, the stop rule is operational, and two reviews close without material surprise.</span></div></Slide>

    <PromptSlide n={13} unit="UNIT 11" title="How should the plan change without making the PM the substitute owner?" output="State the revised sequence, interfaces, decision rights, review cadence, stop condition, and return-to-autonomy condition."><p>Re-sequence the dependency, define the critical interfaces and decision rights, and choose a proportionate review cadence.</p><strong>Name the stop or escalation condition, temporary intervention, and exact condition for returning autonomy.</strong></PromptSlide>

    <Slide n={14} section="UNIT 12  |  CONTROLLED EXPOSURE" title="Deployment, exposure, observed outcome, and durable product impact are four different states" subtitle="Launch is a controlled consequence-and-learning decision—not a binary finish line" source="Reforge, Staging Strategies; Metrics and Instrumentation; Test Impact vs. Actual Impact"><ExhibitTitle n={11}>The outcome chain that prevents premature conclusions</ExhibitTitle><div className="outcome-chain"><article><small>DEPLOYED</small><b>The capability exists in production.</b><p>No user has necessarily encountered it.</p></article><i/><article><small>EXPOSED</small><b>64 eligible meetings across two workspaces could use it.</b><p>Governance blocked one population.</p></article><i/><article><small>OBSERVED</small><b>Confirmed follow-through increased by 3 pp.</b><p>Actor identity is missing for 12% of events.</p></article><i/><article><small>IMPACT</small><b>Durable value, retention, trust, and economics remain unknown.</b><p>Production effect can differ from a bounded test.</p></article></div><div className="implication"><b>Staging job</b><span>Contain downside, preserve rollback, and improve learning—not manufacture a clean success story.</span></div></Slide>

    <Slide n={15} section="UNIT 12  |  FORECAST VS. RESULT" title="The result should update the decision record against what was forecast—not against a story written afterward" subtitle="Population, implementation, instrumentation, and operational conditions explain what the outcome can establish" source="Reforge, Test Impact vs. Actual Impact; Metrics and Instrumentation; course synthesis"><ExhibitTitle n={12}>Noted staged rollout: pre-decision record versus observed evidence</ExhibitTitle><div className="forecast-result"><div className="forecast"><small>FORECAST + RULE</small><b>+8 pp confirmed follow-through</b><p>Expand if the effect clears +5 pp with no trust guardrail decline.</p><ul><li>Two enterprise workspaces</li><li>Known actor + meeting type</li><li>Stable permission path</li></ul></div><i/><div className="result"><small>OBSERVED</small><b>+3 pp overall</b><p>Partner A: +9 pp; Partner B: -1 pp after governance blocked normal use.</p><ul><li>Only 64 eligible meetings exposed</li><li>12% actor identity missing</li><li>Implementation differed by workspace</li></ul></div><i/><div className="update"><small>JUSTIFIED UPDATE</small><b>Do not expand; do not declare failure.</b><p>Continue Partner A, pause Partner B, repair observability and access, then test whether the mechanism transfers.</p></div></div></Slide>

    <Slide n={16} section="UNIT 12  |  DECISION QUALITY" title="A good outcome can follow weak reasoning; a poor outcome can follow a defensible decision" subtitle="Judge the original choice from what was known then, and use the result to update what is known now" source="Reforge, Completing the Decision Loop; OKR Reviews and Post-Mortems; course synthesis"><ExhibitTitle n={13}>Separate outcome quality from decision quality and luck</ExhibitTitle><div className="quality-matrix"><div className="corner"><span>ORIGINAL DECISION</span><span>OUTCOME</span></div><div className="col"><b>Favorable</b><span>Value materialized</span></div><div className="col"><b>Unfavorable</b><span>Value missed or harm appeared</span></div><div className="row"><b>Defensible reasoning</b><span>Evidence, alternatives, uncertainty, and rule were explicit</span></div><article className="learn"><b>Earned progress</b><p>Scale only within the evidence boundary; inspect what was luck.</p></article><article className="learn"><b>Useful loss</b><p>Update the belief without pretending the original call was irrational.</p></article><div className="row"><b>Weak reasoning</b><span>Assumptions hidden; no rule; alternatives ignored</span></div><article className="risk"><b>Lucky win</b><p>Do not institutionalize the decision process that happened to work.</p></article><article className="risk"><b>Predictable failure</b><p>Change both the product choice and the operating system.</p></article></div></Slide>

    <PromptSlide n={17} unit="UNIT 12" title="What did the staged outcome establish—and what should change next?" output="Choose one justified next action. State the evidence boundary, decision-quality judgment, and one operating-system improvement."><p>Separate deploy, exposure, observation, and impact. Compare forecast with result; identify instrumentation, population, implementation, and attribution limits.</p><strong>Choose continue, expand, pause, rollback, reframe, or stop—then name one operating-system improvement.</strong></PromptSlide>

    <Slide n={18} section="SESSION 4  |  CAPSTONE COMPLETE" title="The Product Decision Case closes the original choice without pretending the product story is finished" subtitle="The learner reconstructs one decision from attention through evidence, strategy, commitment, exposure, and learning"><ExhibitTitle n={14}>Completed Product Decision Case</ExhibitTitle><div className="case-complete"><article><span>W1</span><b>Decision + problem</b><p>Boundary, current view, weakest claim, options, and confidence.</p></article><article><span>W2</span><b>Evidence + belief</b><p>Evidence jobs, traceable synthesis, uncertainty, and decision update.</p></article><article><span>W3</span><b>Strategy + constraints</b><p>Direction, exclusions, portfolio, sequence, technical option, and owners.</p></article><article><span>W4</span><b>Commitment + learning</b><p>Rights, dissent, adaptation, exposure, forecast, outcome, and system change.</p></article><div className="checkpoint-output"><small>DEMO DAY STANDARD</small><b>Present the evolution of judgment and the consequential trade-off—not a polished artifact or a build.</b></div></div></Slide>

    <Slide n={19} section="SESSION 4  |  COURSE CLOSE" title="Re-owning the PM core means remaining accountable after the roadmap begins" subtitle="Week 5 Demo Day makes the evolution of judgment visible in six minutes" className="closing"><div className="closing-path"><div><span>PRESENT</span><b>The original decision</b><small>Why it deserved attention and how the problem was earned.</small></div><i className="closing-connector"/><div><span>SHOW</span><b>The belief changes</b><small>Evidence, exclusions, trade-offs, dissent, and constraints.</small></div><i className="closing-connector"/><div className="next"><span>OWN</span><b>The next decision</b><small>What the outcome justifies, what remains uncertain, and what changes now.</small></div></div><div className="closing-note">Demo Day: 6 minutes to present, 4 minutes for live feedback, one Product Decision Case.</div></Slide>
  </main>;
}
