"use client";

/* eslint-disable react/no-unescaped-entities */

import { useEffect } from "react";
import { useSearchParams } from "next/navigation";
import "../../deck/deck.css";
import "../../deck/connectors.css";
import "./session-3.css";

type SlideProps = { n:number; title:string; subtitle?:string; section?:string; source?:string; className?:string; children:React.ReactNode };

function Slide({n,title,subtitle,section="SESSION 3  |  CHOOSE",source,className="",children}:SlideProps){
  return <section className={`consulting-slide ${className}`} id={`slide-${n}`}>
    <header className="slide-header"><div className="section-label">{section}</div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</header>
    <div className="slide-content">{children}</div>
    <footer className="slide-footer"><span>{source?`Source: ${source}`:"Core PM course synthesis"}</span><b>{String(n).padStart(2,"0")}</b></footer>
  </section>;
}
function ExhibitTitle({n,children}:{n:number;children:React.ReactNode}){return <div className="exhibit-title"><b>Exhibit {n}</b><span>{children}</span></div>}
function PromptSlide({n,unit,title,output,children}:{n:number;unit:string;title:string;output:string;children:React.ReactNode}){
  return <Slide n={n} section={`${unit}  |  MAKE THE CALL`} title={title} className="prompt"><div className="prompt-layout"><div className="prompt-flag"><span>INDIVIDUAL DECISION</span><b>06 min</b></div><div className="prompt-question">{children}</div><div className="prompt-output"><span>OUTPUT</span><p>{output}</p></div></div></Slide>
}

export default function Session3Deck(){
  const requestedSlide = Number(useSearchParams().get("export"));
  const exportSlide = Number.isInteger(requestedSlide) && requestedSlide >= 1 && requestedSlide <= 19 ? requestedSlide : null;
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{const forward=["ArrowRight","ArrowDown","PageDown"],backward=["ArrowLeft","ArrowUp","PageUp"];if(![...forward,...backward].includes(event.key))return;event.preventDefault();const slides=[...document.querySelectorAll<HTMLElement>(".consulting-slide")];const current=slides.reduce((best,slide,index)=>Math.abs(slide.getBoundingClientRect().top)<Math.abs(slides[best].getBoundingClientRect().top)?index:best,0);const next=current+(forward.includes(event.key)?1:-1);slides[Math.max(0,Math.min(slides.length-1,next))]?.scrollIntoView({behavior:"smooth"})};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
  return <main className="consulting-deck session-three">
    {exportSlide && <style>{`
      html, body, .consulting-deck { width: 100%; height: 100%; min-height: 0; overflow: hidden; }
      .consulting-deck { display: flex; align-items: center; justify-content: center; }
      .consulting-deck .consulting-slide:not(#slide-${exportSlide}) { display: none; }
      .consulting-deck #slide-${exportSlide} { flex: none; width: 100vw; height: 56.25vw; min-height: 0; }
    `}</style>}
    {!exportSlide && <aside className="deck-controls"><span>Use arrow keys</span><button onClick={()=>document.documentElement.requestFullscreen()}>Fullscreen</button></aside>}

    <Slide n={1} title="Turn evidence into an opinionated choice" subtitle="Session 3 | Convert a calibrated belief into a direction and set of trade-offs worth committing to" className="cover">
      <div className="cover-grid"><div className="cover-number">03</div><div className="cover-steps"><div><span>07</span><b>Choose direction</b><small>Link a diagnosis to a revisable system of strategic hypotheses.</small></div><div><span>08</span><b>Allocate the portfolio</b><small>Fund, sequence, and exclude different forms of product value.</small></div><div><span>09</span><b>Reprice the technical choice</b><small>Use lower production cost without ignoring lifecycle consequence.</small></div></div></div>
    </Slide>

    <Slide n={2} title="Session 3 converts one calibrated belief into choices others can consistently act on" subtitle="Direction constrains allocation; allocation exposes the technical choice; every layer remains revisable">
      <ExhibitTitle n={1}>Cumulative choice architecture</ExhibitTitle><div className="journey"><div className="journey-step"><em>1</em><b>Strategic direction</b><p>Diagnose the constraint and choose a linked winning mechanism with exclusions.</p></div><div className="journey-arrow"/><div className="journey-step"><em>2</em><b>Portfolio and sequence</b><p>Translate the direction into funded work, displaced opportunity, and order.</p></div><div className="journey-arrow"/><div className="journey-step"><em>3</em><b>Technical calculus</b><p>Compare build, buy, adapt, defer, and no-build across lifecycle consequences.</p></div></div><div className="implication"><b>Week 3 output</b><span>A Strategy and Constraint Choice that remains coherent from evidence through ownership.</span></div>
    </Slide>

    <Slide n={3} section="NOTED  |  WEEK 3 CONSTRAINT RELEASE" title="Noted can pursue two credible directions, but it cannot fund both as if no trade-off exists" subtitle="The product context is real; strategic alternatives, capacity, estimates, and constraints are constructed for practice" source="Noted teaching case; product context from noted-main; constraints constructed for practice">
      <ExhibitTitle n={2}>The strategic choice created by the Week 2 belief update</ExhibitTitle><div className="direction-release"><article><small>DIRECTION A · WORKFLOW DEPTH</small><b>Help teams record decisions and assign action owners in recurring enterprise meetings</b><p>Deeper workflow, admin distribution, and governance; narrower initial audience.</p></article><article><small>DIRECTION B · HORIZONTAL BREADTH</small><b>Become a general AI meeting memory for individual knowledge workers</b><p>Faster self-serve reach and broader use cases; weaker connection to decision and owner follow-up.</p></article><div className="constraint-strip"><b>8-WEEK CAPACITY</b><span>2 engineers + 1 designer</span><b>KNOWN LIMIT</b><span>Enterprise security review consumes two weeks</span><b>WEAKEST LINK</b><span>Repeatable admin-led distribution is unproven</span></div><div className="case-call"><b>Decision</b><span>Which direction should govern the next planning cycle—and what must Noted explicitly not pursue?</span></div></div>
    </Slide>

    <Slide n={4} section="UNIT 07  |  DIAGNOSIS" title="Strategy starts by explaining the situation that makes one choice more coherent than another" subtitle="A diagnosis names the consequential constraint; it does not merely restate goals, trends, or customer requests" source="Reforge, Creating Strategic Foundations; Great Product Strategy; course synthesis">
      <ExhibitTitle n={3}>From evidence to a usable diagnosis</ExhibitTitle><div className="diagnosis"><article><small>EVIDENCE</small><b>Unassigned action owners are a plausible source of repeated recap work in decision-heavy meetings.</b><p>Bounded to the target context; causality and prevalence remain incomplete.</p></article><i/><article><small>TENSION</small><b>Noted can add more summary intelligence or make decision and owner follow-up reliable.</b><p>Both create value, but through different audiences and winning mechanisms.</p></article><i/><article className="selected"><small>DIAGNOSIS</small><b>The constraint is not note creation; it is reliably recording each decision and action owner.</b><p>This interpretation makes workflow depth the more coherent next direction.</p></article></div><div className="implication"><b>Judgment remains</b><span>Evidence rules out weak stories; it does not mechanically choose among every plausible interpretation.</span></div>
    </Slide>

    <Slide n={5} section="UNIT 07  |  LINKED HYPOTHESES" title="A strategic direction is only as strong as the links that must all remain credible" subtitle="Audience, problem, value, advantage, growth, and economics form a system—not six independent boxes" source="Reforge, Creating Your Initial PMF Narrative; PMF Narrative Synthesis">
      <ExhibitTitle n={4}>Noted's working strategic hypothesis system</ExhibitTitle><div className="hypothesis-system"><article><small>AUDIENCE</small><b>Enterprise team leads with recurring decision-heavy meetings</b></article><i/><article><small>PROBLEM</small><b>Unassigned actions force teams to reconstruct decisions and miss follow-up</b></article><i/><article><small>VALUE</small><b>A trusted record makes each decision, action owner, and required context retrievable</b></article><i/><article><small>ADVANTAGE</small><b>Noted links the transcript, decision, action owner, and workspace</b></article><i/><article><small>GROWTH</small><b>Admins distribute repeatable templates across recurring meeting types</b></article><i/><article><small>ECONOMICS</small><b>Team-plan willingness supports review, storage, and service cost</b></article></div><div className="system-note"><b>Weakest link</b><span>Admin-led repeatable distribution has not yet been demonstrated.</span><b>System consequence</b><span>If growth fails, value can be real while the direction remains commercially weak.</span></div>
    </Slide>

    <Slide n={6} section="UNIT 07  |  COHERENCE" title="Coherence comes from reinforcing choices, explicit exclusions, and evidence that would force revision" subtitle="A strategy that includes every attractive opportunity does not guide local decisions" source="Reforge, Product Strategy Map; Updating Our PMF Narrative; course synthesis">
      <ExhibitTitle n={5}>Choice, exclusion, and revision make the direction operational</ExhibitTitle><div className="coherence-triad"><article><small>REINFORCING CHOICES</small><b>Prioritize decision-heavy meeting workflows, workspace context, and admin distribution.</b><p>Each investment improves how teams record decisions, assign owners, and complete follow-up.</p></article><article><small>EXPLICIT EXCLUSIONS</small><b>Do not optimize broad personal summarization or expand to every meeting type now.</b><p>Useful demand can still be strategically off-path.</p></article><article><small>REVISION TRIGGERS</small><b>Revisit if admin adoption stalls, governance blocks deployment, or decision-and-owner capture fails to affect repeat use.</b><p>Revision must change a real choice.</p></article></div><div className="implication"><b>Portable test</b><span>Could another team use this direction to reject a locally attractive idea without asking the PM?</span></div>
    </Slide>

    <Slide n={7} section="UNIT 07  |  FIT BOUNDARY" title="No single favorable signal can declare that the strategic system has earned product-market fit" subtitle="Fit is segment- and stage-specific; value, retention, growth, and economics must be read together" source="Reforge, Measuring PMF Deliberately; Measuring Growth, Retention, and Engagement">
      <ExhibitTitle n={6}>Multi-signal boundary for the chosen Noted direction</ExhibitTitle><div className="fit-radar"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-ring r3"/><div className="radar-shape"/><span className="axis a1">Problem intensity <b>STRONGER</b></span><span className="axis a2">Repeat use <b>MIXED</b></span><span className="axis a3">Growth path <b>WEAK</b></span><span className="axis a4">Economics <b>UNKNOWN</b></span><span className="axis a5">Advantage <b>PLAUSIBLE</b></span><div className="fit-boundary"><b>Strategic posture</b><span>Concentrated hypothesis worth testing—not proof of fit or permission to scale.</span></div></div>
    </Slide>

    <PromptSlide n={8} unit="UNIT 07" title="Which strategic direction should govern Noted's next cycle?" output="Choose one direction. State the diagnosis, winning mechanism, explicit exclusion, weakest linked hypothesis, and revision trigger.">
      <p>State the diagnosis, chosen direction, linked winning mechanism, weakest hypothesis, and evidence that changed your view.</p><strong>Name one attractive opportunity you will exclude and one trigger that would reverse the choice.</strong>
    </PromptSlide>

    <Slide n={9} section="UNIT 08  |  PORTFOLIO" title="Different work types create different forms of value; feature work cannot crowd out the rest by default" subtitle="Use portfolio lenses to widen the candidate set, then choose a mix that matches the strategy and stage" source="Reforge, Portfolio of Product Work; Platform and Infrastructure Work; Managing Debt">
      <ExhibitTitle n={7}>Candidate work competing for Noted's constrained cycle</ExhibitTitle><div className="work-types"><article><small>FEATURE</small><b>Decision-and-owner capture</b><p>Records the decision and action owner for later follow-up.</p></article><article><small>GROWTH</small><b>Admin meeting templates</b><p>Tests repeatable workspace distribution.</p></article><article><small>EXPANSION</small><b>Sales call intelligence</b><p>Adds a new use case and audience.</p></article><article><small>SCALE</small><b>Permission model redesign</b><p>Enables enterprise deployment safely.</p></article><article><small>RISK</small><b>Retention and deletion controls</b><p>Reduces security and trust consequence.</p></article><article><small>ENABLING</small><b>Meeting-type instrumentation</b><p>Makes the strategic mechanism observable.</p></article></div><div className="implication"><b>No fixed balance</b><span>The labels make value legible. They do not prescribe equal capacity or protect a bucket from trade-offs.</span></div>
    </Slide>

    <Slide n={10} section="UNIT 08  |  TRANSLATION" title="Strategy becomes real when it changes funding, sequence, and what must wait" subtitle="Repeating a company priority is not product strategy; the PM must translate it into area-level choices" source="Reforge, Identifying Strategic Priorities; Developing a Product Workplan">
      <ExhibitTitle n={8}>From company priority to an opinionated Noted portfolio</ExhibitTitle><div className="allocation"><div className="priority-card"><small>COMPANY PRIORITY</small><b>Earn two enterprise design partners this cycle</b><p>Direction, not a literal backlog instruction.</p></div><i/><div className="allocation-bars"><div><span>Decision + owner capture</span><b style={{width:"88%"}}>34%</b></div><div><span>Permission + governance</span><b style={{width:"70%"}}>27%</b></div><div><span>Admin distribution test</span><b style={{width:"58%"}}>22%</b></div><div><span>Instrumentation</span><b style={{width:"44%"}}>17%</b></div></div><div className="deferred"><small>EXPLICITLY DISPLACED</small><b>Sales intelligence</b><b>Personal summary polish</b><b>Full architecture modernization</b></div></div><div className="implication"><b>Portfolio choice</b><span>Percentages communicate emphasis, not a false promise of precise capacity accounting.</span></div>
    </Slide>

    <Slide n={11} section="UNIT 08  |  PRIORITIZATION" title="A score can expose assumptions; it cannot absorb responsibility for the decision" subtitle="When inputs are invented or strategic fit is flattened, numerical precision hides the actual trade-off" source="Reforge, The Problem with RICE; Prioritizing Objectives and Initiatives; course synthesis">
      <ExhibitTitle n={9}>The highest score is not automatically the coherent choice</ExhibitTitle><div className="score-table"><div className="score-head"><span>Candidate</span><span>Reach</span><span>Impact</span><span>Confidence</span><span>Effort</span><span>Score</span><span>Strategic issue</span></div><div><b>Summary polish</b><span>9</span><span>7</span><span>8</span><span>3</span><strong>168</strong><em>Broad reach, weak connection to decision and owner follow-up</em></div><div className="chosen"><b>Permission redesign</b><span>4</span><span>9</span><span>6</span><span>6</span><strong>36</strong><em>Lower score; removes enterprise adoption constraint</em></div><div><b>Meeting-type instrumentation</b><span>3</span><span>6</span><span>5</span><span>3</span><strong>30</strong><em>Creates evidence and option value</em></div><div><b>Sales intelligence</b><span>7</span><span>8</span><span>4</span><span>7</span><strong>32</strong><em>Attractive expansion; contradicts current focus</em></div></div><div className="implication"><b>Use the score</b><span>Interrogate reach, impact, confidence, and effort—then make the strategy-aware call explicitly.</span></div>
    </Slide>

    <Slide n={12} section="UNIT 08  |  SEQUENCE" title="Sequence should buy learning and preserve options before it creates irreversible commitment" subtitle="Dependencies, evidence value, reversibility, and time-to-value matter alongside urgency" source="Reforge, Developing a Product Workplan; Break Up Problems and Sequence Work; course synthesis">
      <ExhibitTitle n={10}>A value-bearing sequence for Noted's next eight weeks</ExhibitTitle><div className="sequence"><article><small>WEEKS 1-2</small><b>Instrument the meeting type and test the admin template manually</b><p>Cheapest evidence on the weakest growth link.</p></article><i/><article><small>WEEKS 2-4</small><b>Ship explicit decision-and-owner capture to two design partners</b><p>Tests the core mechanism in a bounded context.</p></article><i/><article><small>WEEKS 3-6</small><b>Implement minimum permission and retention controls</b><p>Enables credible use without building the full platform.</p></article><i/><article><small>WEEKS 7-8</small><b>Choose deepen, expand, or stop from observed use</b><p>Preserves a real revision point before scale.</p></article></div><div className="option-value"><b>Option created</b><span>Evidence can justify deeper platform work later.</span><b>Commitment avoided</b><span>No full enterprise architecture before the workflow earns it.</span></div>
    </Slide>

    <PromptSlide n={13} unit="UNIT 08" title="What portfolio mix and sequence should make the strategy real?" output="Choose one portfolio and sequence. State funded work, displaced opportunity, owner, learning logic, and revision point.">
      <p>Fund a bounded mix across the candidates. Explain the value contribution, dependency, learning logic, and owner for each commitment.</p><strong>State the most painful displaced opportunity and why the roadmap score does not own your call.</strong>
    </PromptSlide>

    <Slide n={14} section="UNIT 09  |  AI-ERA CALCULUS" title="Coding agents lower the cost of producing plausible software—not the full cost of product ownership" subtitle="The bottleneck can move from generation toward context, evaluation, integration, release, and operation" source="Reforge Technical Strategy; Anthropic Economic Index (2025); METR (2025)">
      <ExhibitTitle n={11}>The production-cost curve moved; lifecycle consequence did not disappear</ExhibitTitle><div className="cost-shift"><div className="before"><small>BEFORE AGENTS</small><span>Define</span><span className="large">Produce</span><span>Review</span><span>Integrate</span><span>Operate</span></div><div className="after"><small>WITH AGENTS</small><span>Define</span><span className="small">Produce</span><span className="large">Review</span><span className="large">Integrate</span><span>Operate</span></div><div className="evidence-caution"><b>Current evidence is context-dependent</b><p>Large-scale usage shows coding is a major agent use case. A randomized study of experienced maintainers in mature repositories found early-2025 tools slowed the measured work. Do not convert capability into a universal productivity promise.</p></div></div>
    </Slide>

    <Slide n={15} section="UNIT 09  |  BUILD / BUY / ADAPT" title="Lower generation cost changes the inputs—but differentiation and lifecycle ownership still govern the option" subtitle="Compare build, buy, adapt, defer, and no-build against one explicit product capability" source="Reforge, Build or Buy Trade-Offs; Finance Decision Rubric; course synthesis">
      <ExhibitTitle n={12}>Decision-and-owner extraction option matrix</ExhibitTitle><div className="lifecycle-matrix"><div className="life-head"><span>Option</span><span>Differentiation</span><span>Time to evidence</span><span>Integration + data</span><span>Ongoing owner</span><span>Position</span></div><div><b>Build with agent support</b><span>High potential</span><span>Fast prototype</span><span>High context burden</span><span>Noted engineering</span><em>ADAPT</em></div><div className="chosen"><b>Adapt a model API</b><span>Keep workflow logic in-house</span><span>Fastest bounded test</span><span>Vendor + governance risk</span><span>Named platform owner</span><em>STAGE</em></div><div><b>Buy end-to-end</b><span>Low control</span><span>Fast deployment</span><span>Deep vendor lock-in</span><span>Vendor + Noted ops</span><em>DEFER</em></div><div><b>No-build workflow</b><span>Tests whether explicit decisions and owners change follow-up</span><span>Immediate</span><span>Manual operating cost</span><span>PM + design partner</span><em>FIRST</em></div></div>
    </Slide>

    <Slide n={16} section="UNIT 09  |  THRESHOLDS + SLICES" title="Technical work earns capacity through a named consequence, threshold, and smaller value-bearing sequence" subtitle="“Tech debt,” future scale, and a fast prototype are not self-justifying arguments" source="Reforge, Limitations of Tech Debt; Scale and Risk Thresholds; Break Up Problems and Sequence Work">
      <ExhibitTitle n={13}>From labels to accountable technical choices</ExhibitTitle><div className="thresholds"><article><small>RISK THRESHOLD</small><b>No pilot with customer recordings until retention, deletion, and access controls pass review.</b><p>Consequence: trust, contractual, and security exposure.</p></article><article><small>SCALE THRESHOLD</small><b>Do not build a multi-region pipeline before concurrent processing or latency blocks the target workflow.</b><p>Consequence: premature infrastructure commitment.</p></article><article><small>ECONOMIC THRESHOLD</small><b>Revisit vendor versus owned inference when unit cost or gross margin crosses the named bound.</b><p>Consequence: value creation without viable capture.</p></article></div><div className="slice-path"><b>Manual workflow test</b><i/><b>API-assisted shadow mode</b><i/><b>Two-partner bounded pilot</b><i/><b>Operationalize only after thresholds</b></div>
    </Slide>

    <PromptSlide n={17} unit="UNIT 09" title="What should Noted build, buy, adapt, defer, or not build?" output="Choose one technical option. State lifecycle consequence, threshold, smaller sequence, specialist review, and operational owner.">
      <p>Choose one option for extracting and recording decisions and action owners. State what coding agents change, what remains costly, and where scope, time, quality, or ownership risk moves.</p><strong>Name the threshold, smallest value-bearing sequence, specialist review, and operational owner.</strong>
    </PromptSlide>

    <Slide n={18} section="SESSION 3  |  CAPSTONE CHECKPOINT" title="The Week 3 record carries one coherent choice from diagnosis through lifecycle consequence" subtitle="A strategy is portable when another team can act—and decline work—without inventing the missing logic">
      <ExhibitTitle n={14}>Strategy and Constraint Choice</ExhibitTitle><div className="checkpoint-grid"><article><span>01</span><b>Diagnosis + direction</b><p>Situation, winning mechanism, linked hypotheses, weakest link, and exclusions.</p></article><article><span>02</span><b>Portfolio choice</b><p>Funded value types, displaced opportunity, capacity emphasis, and owners.</p></article><article><span>03</span><b>Strategic sequence</b><p>Dependencies, learning order, option value, and revision points.</p></article><article><span>04</span><b>Technical calculus</b><p>Option, lifecycle consequences, thresholds, specialist review, and operational owner.</p></article><div className="checkpoint-output"><small>HANDOFF TO SESSION 4</small><b>One direction people can commit to, adapt without reclaiming ownership, and evaluate without rewriting history.</b></div></div>
    </Slide>

    <Slide n={19} section="SESSION 3  |  CLOSE" title="An opinionated choice is not certainty; it is coherent commitment with visible conditions" subtitle="Session 4 will turn the choice into commitment, preserve ownership through adaptation, and close the learning loop" className="closing"><div className="closing-path"><div><span>CARRY FORWARD</span><b>Chosen direction</b><small>What wins, what waits, and which linked assumption is weakest.</small></div><i className="closing-connector"/><div><span>MAKE PORTABLE</span><b>Constraints + ownership</b><small>Funded work, sequence, thresholds, and accountable owners.</small></div><i className="closing-connector"/><div className="next"><span>SESSION 4</span><b>Commit and learn</b><small>Create alignment for action without requiring consensus or hindsight.</small></div></div><div className="closing-note">Bring the choice record—not a polished roadmap—to the commitment conversation.</div></Slide>
  </main>;
}
